var searchData=
[
  ['cdata_616',['cdata',['../structhr_1_1cdata.html',1,'hr']]],
  ['cell_617',['cell',['../structhr_1_1cell.html',1,'hr']]],
  ['celldrawer_618',['celldrawer',['../structhr_1_1celldrawer.html',1,'hr']]],
  ['cellinfo_619',['cellinfo',['../structhr_1_1irr_1_1cellinfo.html',1,'hr::irr']]],
  ['celllister_620',['celllister',['../structhr_1_1celllister.html',1,'hr']]],
  ['cellrotation_5ft_621',['cellrotation_t',['../structhr_1_1geometry__information_1_1cellrotation__t.html',1,'hr::geometry_information']]],
  ['changeable_5fpattern_622',['changeable_pattern',['../structhr_1_1patterns_1_1changeable__pattern.html',1,'hr::patterns']]],
  ['changeable_5fpattern_5fgeometry_623',['changeable_pattern_geometry',['../structhr_1_1patterns_1_1changeable__pattern__geometry.html',1,'hr::patterns']]],
  ['changes_5ft_624',['changes_t',['../structhr_1_1changes__t.html',1,'hr']]],
  ['chargedata_625',['chargedata',['../structhr_1_1elec_1_1chargedata.html',1,'hr::elec']]],
  ['charstyle_626',['charstyle',['../structhr_1_1charstyle.html',1,'hr']]],
  ['charstyle_5fold_627',['charstyle_old',['../structhr_1_1charstyle__old.html',1,'hr']]],
  ['clearingdata_628',['clearingdata',['../structhr_1_1clearing_1_1clearingdata.html',1,'hr::clearing']]],
  ['code_629',['code',['../structhr_1_1quotientspace_1_1code.html',1,'hr::quotientspace']]],
  ['colored_5fvertex_630',['colored_vertex',['../structhr_1_1glhr_1_1colored__vertex.html',1,'hr::glhr']]],
  ['colortable_631',['colortable',['../structhr_1_1colortable.html',1,'hr']]],
  ['comma_5fprinter_632',['comma_printer',['../structhr_1_1comma__printer.html',1,'hr']]],
  ['config_633',['config',['../structhr_1_1multi_1_1config.html',1,'hr::multi']]],
  ['connection_5ftable_634',['connection_table',['../structhr_1_1connection__table.html',1,'hr']]],
  ['connection_5ftable_3c_20hr_3a_3acell_20_3e_635',['connection_table&lt; hr::cell &gt;',['../structhr_1_1connection__table.html',1,'hr']]],
  ['connection_5ftable_3c_20hr_3a_3aheptagon_20_3e_636',['connection_table&lt; hr::heptagon &gt;',['../structhr_1_1connection__table.html',1,'hr']]],
  ['coord_637',['coord',['../structhr_1_1euc_1_1coord.html',1,'hr::euc::coord'],['../structhr_1_1crystal_1_1coord.html',1,'hr::crystal::coord'],['../structhr_1_1asonov_1_1coord.html',1,'hr::asonov::coord']]],
  ['crystal_5fstructure_638',['crystal_structure',['../structhr_1_1crystal_1_1crystal__structure.html',1,'hr::crystal']]],
  ['ct_5fvertex_639',['ct_vertex',['../structhr_1_1glhr_1_1ct__vertex.html',1,'hr::glhr']]]
];
