var searchData=
[
  ['cdata_601',['cdata',['../structhr_1_1cdata.html',1,'hr']]],
  ['cell_602',['cell',['../structhr_1_1cell.html',1,'hr']]],
  ['celldrawer_603',['celldrawer',['../structhr_1_1celldrawer.html',1,'hr']]],
  ['cellinfo_604',['cellinfo',['../structhr_1_1irr_1_1cellinfo.html',1,'hr::irr']]],
  ['celllister_605',['celllister',['../structhr_1_1celllister.html',1,'hr']]],
  ['cellrotation_5ft_606',['cellrotation_t',['../structhr_1_1geometry__information_1_1cellrotation__t.html',1,'hr::geometry_information']]],
  ['changeable_5fpattern_607',['changeable_pattern',['../structhr_1_1patterns_1_1changeable__pattern.html',1,'hr::patterns']]],
  ['changeable_5fpattern_5fgeometry_608',['changeable_pattern_geometry',['../structhr_1_1patterns_1_1changeable__pattern__geometry.html',1,'hr::patterns']]],
  ['changes_5ft_609',['changes_t',['../structhr_1_1changes__t.html',1,'hr']]],
  ['chargedata_610',['chargedata',['../structhr_1_1elec_1_1chargedata.html',1,'hr::elec']]],
  ['charstyle_611',['charstyle',['../structhr_1_1charstyle.html',1,'hr']]],
  ['charstyle_5fold_612',['charstyle_old',['../structhr_1_1charstyle__old.html',1,'hr']]],
  ['clearingdata_613',['clearingdata',['../structhr_1_1clearing_1_1clearingdata.html',1,'hr::clearing']]],
  ['code_614',['code',['../structhr_1_1quotientspace_1_1code.html',1,'hr::quotientspace']]],
  ['colored_5fvertex_615',['colored_vertex',['../structhr_1_1glhr_1_1colored__vertex.html',1,'hr::glhr']]],
  ['colortable_616',['colortable',['../structhr_1_1colortable.html',1,'hr']]],
  ['comma_5fprinter_617',['comma_printer',['../structhr_1_1comma__printer.html',1,'hr']]],
  ['config_618',['config',['../structhr_1_1multi_1_1config.html',1,'hr::multi']]],
  ['connection_5ftable_619',['connection_table',['../structhr_1_1connection__table.html',1,'hr']]],
  ['connection_5ftable_3c_20hr_3a_3acell_20_3e_620',['connection_table&lt; hr::cell &gt;',['../structhr_1_1connection__table.html',1,'hr']]],
  ['connection_5ftable_3c_20hr_3a_3aheptagon_20_3e_621',['connection_table&lt; hr::heptagon &gt;',['../structhr_1_1connection__table.html',1,'hr']]],
  ['coord_622',['coord',['../structhr_1_1euc_1_1coord.html',1,'hr::euc::coord'],['../structhr_1_1crystal_1_1coord.html',1,'hr::crystal::coord'],['../structhr_1_1asonov_1_1coord.html',1,'hr::asonov::coord']]],
  ['crystal_5fstructure_623',['crystal_structure',['../structhr_1_1crystal_1_1crystal__structure.html',1,'hr::crystal']]],
  ['ct_5fvertex_624',['ct_vertex',['../structhr_1_1glhr_1_1ct__vertex.html',1,'hr::glhr']]]
];
